replicaCount: 1
bot:
  repository: harbor.sheldan.dev/crimson
  pullPolicy: Always
  image: crimson-bot
  tag: 1.0.0
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 5
    failureThreshold: 3
  propertyConfig:
    hikariPoolSize: 10
  host: null
privateRestApi:
  enabled: true
  repository: harbor.sheldan.dev/crimson
  pullPolicy: Always
  image: crimson-private-rest-api
  tag: 1.0.0
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  livenessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    failureThreshold: 3
  service:
    port: 8080
    targetPort: 80
    name: private-restapi
  resources:
    limits:
      cpu: null
      memory: null
    requests:
      cpu: null
      memory: null
  nodeSelector: {}
  tolerations: []
  affinity: {}
templateDeployment:
  enabled: true
  repository: harbor.sheldan.dev/abstracto
  pullPolicy: Always
  image: abstracto-template-deployment
  tag: 1.6.0
templateDeploymentData:
  repository: harbor.sheldan.dev/crimson
  pullPolicy: Always
  image: crimson-template-data
  tag: 1.0.0
dbConfigDeployment:
  enabled: true
  repository: harbor.sheldan.dev/abstracto
  pullPolicy: Always
  image: abstracto-db-deployment
  tag: 1.6.0
dbConfigDeploymentData:
  repository: harbor.sheldan.dev/crimson
  pullPolicy: Always
  image: crimson-db-data
  tag: 1.0.0
dbCredentials:
  host: null
  port: null
  userName: null
  password: null
  name: null
  schema: abstracto
apiKeys:
  discord:
    token: null
  youtube:
    apiKey: null
  openWeatherMap:
    apiKey: null
  freeCurrencyApi:
    apiKey: null
imagePullSecrets: null
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: '8080'
resources:
  limits:
    cpu: null
    memory: null
  requests:
    cpu: null
    memory: null
nodeSelector: {}
tolerations: []
affinity: {}
